# Generated by Django 5.0.6 on 2024-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_discount_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='discount in %'),
        ),
    ]
